pipeline {
	agent any

	stages {
		stage ('Initialize') {
		      steps {
		        sh '''
                		echo "PATH = ${PATH}"
		                echo "M2_HOME = ${M2_HOME}"
		            ''' 
      			}
    		}
		
		stage('Compile Stage'){
			steps{
				withMaven(maven: 'maven_3_6_3'){
						sh 'cd webGoat'
						sh 'mvn clean install -DskipTests'
					}
				}
			}
		}
}
